# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab37c670cbbc3d8e59fcfecbe1cddc049d91480fe33a7ea290e7daab27e37896a62a51dc096965279f2114c22865904332b289bce3bf356e626bd3eab84379a0

test:
  secret_key_base: 99b8cabebd4e40d1de4e9b60a2e2751e23874bfcfb6a1df5aea7fe777f1ced836db9437ec3e5a5e66bc637924352e3fdfa3729050d7fd91d77b53a93e054580f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
